# Generated by Django 3.0.6 on 2021-01-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('phone', models.IntegerField(default='', max_length=10)),
                ('address', models.TextField(default='')),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
