# Generated by Django 3.0.6 on 2021-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactPageApp', '0005_auto_20210127_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactdata',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
